# Build and Deploy Workflow
#
# This workflow handles the continuous integration and deployment process for the TRMNL Salah Times project.
# It follows a trunk-based development approach where:
# - All branch pushes are tested to provide early feedback
# - All PRs to main are validated before merging
# - Only changes to the main branch are deployed to production

name: Build and Deploy

# Workflow Triggers
on:
  push:
    branches:
      - '**'  # Run on all branch pushes (including main)
  pull_request:
    branches:
      - main   # Run on PRs targeting the main branch

jobs:
  # Job: Test & Validate
  # Purpose: Ensure code quality by running tests, type checking, and linting
  # Runs on: All branch pushes and PRs to main
  test-and-validate:
    name: Test & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development stack
        run: supabase db start

      - name: Check types
        run: yarn check-types

      - name: Lint code
        run: yarn lint

      - name: Run tests
        env:
          SUPABASE_URL: http://127.0.0.1:54321
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
        run: yarn test

  # Job: Deploy to Production
  # Purpose: Deploy the application to AWS using Serverless Framework with stage=prod
  # Runs on: Only pushes to the main branch
  deploy:
    name: Deploy to Production
    needs: test-and-validate  # Only run if tests pass
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on main branch pushes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TrmnlSalahTimesDeployRole
          aws-region: eu-west-2  # AWS region for deployment

      - name: Deploy to AWS (Production)
        run: yarn serverless:deploy --stage prod
        env:
          TRMNL_CLIENT_ID: ${{ secrets.TRMNL_CLIENT_ID }}
          TRMNL_CLIENT_SECRET: ${{ secrets.TRMNL_CLIENT_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
